#!/usr/bin/env php
<?php
// no error handling yet

$list = file_get_contents("https://www.pspad.com/cz/download.php");
preg_match_all("~/files/dic/([a-z]+)_dic.cab~", $list, $packs, PREG_SET_ORDER);

$srclist = [];
$srclist[] = 'pspaden_x64.zip::https@subdir://www.pspad.com/files/pspad/pspad$(echo "${pkgver}" | sed -r \'s/^([0-9]+)[.]([0-9]+)[.]([0-9]+)[.]([0-9]+)$/\\1\\2\\3/\')en_x64.zip';

foreach ($packs as $pack) {
	list($lang) = array_slice($pack, 1);
	echo "Found: {$lang}_dic.cab\n";
	$srclist[] = "{$lang}_dic.cab::https://www.pspad.com/files/dic/{$lang}_dic.cab";
}

$srclist = ltrim(implode("\n", array_map(function($src) { return "        \"{$src}\""; }, $srclist)));
$pkgbuild = file_get_contents('PKGBUILD');
$pkgbuild = preg_replace("~^source=\(.*?\)$~sm", addcslashes("source=({$srclist})", '\\$'), $pkgbuild);
rename('PKGBUILD', 'PKGBUILD.old');
file_put_contents('PKGBUILD', $pkgbuild);
