#!/usr/bin/env php
<?php
// no error handling yet

$list = file_get_contents("http://www.pspad.com/cz/download.php");
preg_match_all("~http://www.pspad.com/files/dic/([a-z]+)_dic.cab~", $list, $packs, PREG_SET_ORDER);

$srclist = [];
$srclist[] = 'pspaden.zip::http://www.pspad.com/files/pspad/pspad${pkgver//./}en.zip';

foreach ($packs as $pack) {
	list($lang) = array_slice($pack, 1);
	echo "Found: {$lang}_dic.cab\n";
	$srclist[] = "{$lang}_dic.cab::http://www.pspad.com/files/dic/{$lang}_dic.cab";
}

$srclist = ltrim(implode("\n", array_map(function($src) { return "        \"{$src}\""; }, $srclist)));
$pkgbuild = file_get_contents('PKGBUILD');
$pkgbuild = preg_replace("~source=\(.*?\)~s", "source=({$srclist})", $pkgbuild);
rename('PKGBUILD', 'PKGBUILD.old');
file_put_contents('PKGBUILD', $pkgbuild);
