#!/usr/bin/env php
<?php
// no error handling yet

$list = file_get_contents("https://jsware.net/jsware/msicode.php5");
preg_match_all("~/jsware/zips/([A-Za-z0-9]+)[.]zip~", $list, $zips, PREG_SET_ORDER);

$srclist = [];

foreach ($zips as $zip) {
	list($name) = array_slice($zip, 1);
	echo "Found: {$name}.zip\n";
	$subdir = $name === 'jsmsix19' ? '@subdir' : '';
	$srclist[] = "{$name}.zip::https{$subdir}://www.jsware.net/jsware/zips/{$name}.zip";
}

$srclist = ltrim(implode("\n", array_map(function($src) { return "        \"{$src}\""; }, $srclist)));
$pkgbuild = file_get_contents('PKGBUILD');
$pkgbuild = preg_replace("~source=\(.*?\)~s", "source=({$srclist})", $pkgbuild);
rename('PKGBUILD', 'PKGBUILD.old');
file_put_contents('PKGBUILD', $pkgbuild);
