#!/usr/bin/env php
<?php
// no error handling yet

$context = stream_context_create([ 'http' => [ 'header' => 'Referer: http://www.cheater.cz/' ] ]);

$list = file_get_contents("http://www.cheater.cz/wincheater2/download-knihovny/");
preg_match_all("~<a onclick=\"downloadx\('(.*?)'\)\"~", $list, $matches);

$srclist = [];
foreach ($matches[1] as $libraryname) {
	$filename = file_get_contents("http://www.cheater.cz/download/get-name.php?soubor={$libraryname}", false, $context);
	if ($filename === '????') {
		$filename = "{$libraryname}.exe";
	}
	$link = file_get_contents("http://www.cheater.cz/download/get-link.php?soubor={$libraryname}", false, $context);
	preg_match("~hash=([a-z0-9]+)~", $link, $match);
	$hash = $match[1];
	echo "Found: {$filename}\n";
	$srclist[] = "{$filename}::http://www.cheater.cz/download/download-file.php?hash={$hash}";
}

$srclist = ltrim(implode("\n", array_map(function($src) { return "        \"{$src}\""; }, $srclist)));
$pkgbuild = file_get_contents('PKGBUILD');
$pkgbuild = preg_replace("~source=\(.*?\)~s", "source=({$srclist})", $pkgbuild);
rename('PKGBUILD', 'PKGBUILD.old');
file_put_contents('PKGBUILD', $pkgbuild);
